# Generated by Django 3.2.9 on 2022-03-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Em_name', models.CharField(max_length=40)),
                ('Em_company_name', models.CharField(max_length=40)),
                ('Em_Sallary', models.IntegerField()),
            ],
        ),
    ]
